### ISSUE TITLE
stoped working, it wont download anything, couldyou please take a look?

### ISSUE THREAD

**Issue by julio213180** [n0l3r/tiktok-downloader#18]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by tempus099** [comment]
Same thing happened to me. Seems to be an issue with the res.aweme_list[0] part. Something is up with the API url I think.

**Comment by brotherblackdog** [comment]
Same here:

Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideoNoWM (/Users/nanak/tiktok-downloader/index.js:110:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/nanak/tiktok-downloader/index.js:214:89
Response body:
/Users/nanak/tiktok-downloader/index.js:115
                const urlMedia = res.aweme_list[0].video.play_addr.url_list[0]
                                     ^

TypeError: Cannot read properties of undefined (reading 'aweme_list')
    at getVideoNoWM (/Users/nanak/tiktok-downloader/index.js:115:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /Users/nanak/tiktok-downloader/index.js:214:89

Node.js v19.5.0

**Comment by estatistics** [comment]
same here... it founds the videos but non is downloaded

**Comment by tbm** [comment]
Same for me:

```
[*] Getting list video from: XXXX
[*] 16 video found
[*] 30 video found
[*] 30 video found
[X] No more video found
[*] Total video found: 30
[!] Found 30 video
Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideoNoWM (/home/tbm/src/tiktok-downloader/index.js:110:33)

    at async /home/tbm/src/tiktok-downloader/index.js:214:89
Response body: 
(node:1259272) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'aweme_list' of undefined
    at getVideoNoWM (/home/tbm/src/tiktok-downloader/index.js:115:38)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async /home/tbm/src/tiktok-downloader/index.js:214:89
```

**Comment by quanth1508** [comment]
Same thing happened to me, i not working when i any action download, hope anyone fix bug will be honored.  There is log error:

Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideoNoWM (/*****/tiktok-downloader/index.js:110:33)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /****/tiktok-downloader/index.js:214:89
Response body: 
/***/TikTok/tiktok-downloader/index.js:115
                const urlMedia = res.aweme_details[0].video.play_addr.url_list[0]
                                     ^

TypeError: Cannot read properties of undefined (reading 'aweme_details')
    at getVideoNoWM (/***/tiktok-downloader/index.js:115:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async /***/tiktok-downloader/index.js:214:89

**Comment by matthewcoolio** [comment]
Made a fix for it, seems the api link was expired so I changed the link and it all works fine for me!

**Comment by tbm** [comment]
@matthewcoolio can you open a PR or where can we find your fix?

**Comment by n0l3r** [comment]
I have solved this problem. please re-clone this repository. Thank u :)

**Comment by julio213180** [comment]
Nice, thank you
