### ISSUE TITLE
Hello, i'm getting error while downloading a single video. 

### ISSUE THREAD

**Issue by fallabdoulaye93** [n0l3r/tiktok-downloader#5]
**Describe the bug**

**Expected behavior**

**Screenshots**

**Additional context**

 return Body.Promise.reject(new FetchError(`invalid json response body at ${_this2.url} reason: ${err.message}`, 'invalid-json'));
                                                           ^
FetchError: invalid json response body at https://api.tiktokv.com/aweme/v1/multi/aweme/detail/?aweme_ids=%5B7121740182239317253%5b reason: Unexpected end of JSON input
    at /Applications/MAMP/htdocs/temp/tiktok-downloader/node_modules/node-fetch/lib/index.js:273:32
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getVideoNoWM (/Applications/MAMP/htdocs/temp/tiktok-downloader/index.js:98:17)
    at async /Applications/MAMP/htdocs/temp/tiktok-downloader/index.js:196:89 {
  type: 'invalid-json'
}

**Comment by pratamaid** [comment]
That's because the API from https://api.tiktokv.com can't be used anymore

**Comment by kwstasna** [comment]
> 

Is there any alternative way?
