### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Antonin2938** [n0l3r/tiktok-downloader#59]
I have a problem, in all the modes. When I would like to download, this appears :

Error: SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at getVideo (C:\Users\antob\Downloads\TikTok\tiktok-downloader\index.js:126:24)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\antob\Downloads\TikTok\tiktok-downloader\index.js:320:20
Response body:
C:\Users\antob\Downloads\TikTok\tiktok-downloader\index.js:133
    if (res.aweme_list[0].aweme_id != idVideo) {
            ^

TypeError: Cannot read properties of undefined (reading 'aweme_list')
    at getVideo (C:\Users\antob\Downloads\TikTok\tiktok-downloader\index.js:133:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\antob\Downloads\TikTok\tiktok-downloader\index.js:320:20

**Comment by adonischirinos** [comment]
It's a tiktok endpoint API problem, it affects us all. See #50
